#!/bin/bash
FSTAB_FILE="/home/matthias/git/config/README.md"
USER="/home/matthias"
AWESOME="$USER/.config/awesome"
AWESOME_TEST="/home/matthias/git/config/awesome"
NAS_MYDIR="/home/matthias/Syno*"
NAS=`ls -d $NAS_MYDIR | egrep '^d' | awk '{print $8}'`
GITCONFIG_FOLDER="$USER/git/config/"



if [ -d "$AWESOME_TEST"]; then
cd /home/matthias/git/config
rm -R $AWESOME_TEST
git clone https://github.com/hidekin/awesomeConfig.git

mv $USER/git/config/awesomeConfig $USER/.config/awesome
fi


if [ !  -d "$NAS" ]; then
    
mkdir $USER/SynoDocs
mkdir $USER/SynoDownloads
mkdir $USER/SynoTransmission
mkdir $USER/SynoVideo
mkdir $USER/SynoPhoto
mkdir $USER/SynoWeb
mkdir $USER/SynoHome
mkdir $USER/SynoMusic
mkdir $USER/SynoHome
mkdir $USER/SynoBackup




fi



cp $USER/git/config/.synology.cred $USER





echo "//192.168.1.4/video    /home/matthias/SynoVideo        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/photo    /home/matthias/SynoPhoto        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/music    /home/matthias/SynoMusic        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/Documents    /home/matthias/SynoDocs        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/Backup    /home/matthias/SynoBackup        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/web    /home/matthias/SynoWeb        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/downloads    /home/matthias/SynoDownloads        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/homes    /home/matthias/SynoHome        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE
echo "//192.168.1.4/transmission    /home/matthias/SynoTransmission        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0" >>$FSTAB_FILE


