#!/bin/bash
$USERPATH=/home/matthias/
$AWESOME=$USERPATH/.config/awesome/
if[-d "$AWESOME"]; then
      rm -R ~/.config/awesome/
      git clone https://github.com/hidekin/awesomeConfig.git
	cd $USERPATH/.config/
	mv awesomeConfig/ awesome/		
fi



mkdir ~/SynoDocs
mkdir ~/SynoDownloads
mkdir ~/SynoTransmission
mkdir ~/SynoVideo
mkdir ~/SynoPhoto
mkdir ~/SynoWeb
mkdir ~/SynoHome
mkdir ~/SynoMusic
mkdir ~/SynoHome
mkdir ~/SynoBackup

cp ~/git/config/.synology.cred ~/



echo " //192.168.1.4/video    /home/matthias/SynoVideo        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0 " >>~/README.md
#//192.168.1.4/photo    /home/matthias/SynoPhoto        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0
#//192.168.1.4/music    /home/matthias/SynoMusic        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0
#//192.168.1.4/Documents    /home/matthias/SynoDocs        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0
#//192.168.1.4/Backup    /home/matthias/SynoBackup        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0
#//192.168.1.4/web    /home/matthias/SynoWeb        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0
#//192.168.1.4/downloads    /home/matthias/SynoDownloads        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0
#//192.168.1.4/homes    /home/matthias/SynoHome        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0
#//192.168.1.4/transmission    /home/matthias/SynoTransmission        cifs    credentials=/home/matthias/.synology.cred,users,noauto,_netdev,noserverino,nounix,iocharset=utf8,gid=root,uid=matthias,file_mode=0777,dir_mode=0777 0 0

